/**
 * lessons-index.mjs — print the team-lessons failure catalog for injection by
 * a Claude Code hook (`SessionStart` / `SubagentStart`).
 *
 * WHY THIS EXISTS
 * The catalog generated by `gen-lessons.mjs` lives inside `SKILL.md`, which an
 * agent only reads if it decides to open the skill. A hook that runs on every
 * session/subagent start and prints the catalog to stdout gets it into context
 * unconditionally, the same way the orchestrator already injects playbook
 * rules into delegation prompts. This script is the thing a hook shells out to
 * — it does no generation of its own, it only extracts what `gen-lessons.mjs`
 * already committed to `SKILL.md`.
 *
 * USAGE (as a Claude Code hook command)
 *   node .claude/skills/team-lessons/scripts/lessons-index.mjs
 *
 * DESIGN NOTES
 * - Reuses `CATALOG_START` / `CATALOG_END` (and `EMPTY_CATALOG`, and
 *   `resolvePaths`) from `gen-lessons.mjs` instead of redeclaring them, so the
 *   marker strings and path-resolution rule have exactly one owner. If either
 *   ever changes, this file does not need to.
 * - `extractCatalog` is a pure function (string in, string out) so it can be
 *   unit-tested directly, independent of the filesystem and of exit codes.
 * - Every failure mode a hook can hit — no `SKILL.md` yet, missing/reordered
 *   markers, an empty catalog (`(none yet)`) — resolves to exit 0 with no
 *   output. A hook failing (or a hook printing noise into a project that has
 *   not recorded a single lesson yet) is worse than a hook that silently does
 *   nothing: it must never be able to break a session. Read errors (e.g.
 *   permissions) are caught for the same reason.
 * - `import.meta.dirname` needs Node >= 20.11; this package's `engines` allows
 *   Node 18, so resolve the CLI-entry check the same way the rest of the repo
 *   does: derive it from `import.meta.url` instead.
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { CATALOG_START, CATALOG_END, EMPTY_CATALOG, resolvePaths } from './gen-lessons.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Extract the catalog body between the markers in a SKILL.md's full text.
 *
 * @param {string} skillContent full text of SKILL.md
 * @returns {string} the trimmed catalog body, or '' if the markers are
 *   missing/reordered, or if the catalog is the empty-state placeholder.
 */
export function extractCatalog(skillContent) {
  const normalized = skillContent.replace(/\r\n/g, '\n');

  const startIndex = normalized.indexOf(CATALOG_START);
  const endIndex = normalized.indexOf(CATALOG_END);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    return '';
  }

  const rawBody = normalized.slice(startIndex + CATALOG_START.length, endIndex);

  // `SKILL.md` is user-owned: gen-lessons.mjs only writes it when it is
  // absent, so an already-scaffolded project's SKILL.md is never force-
  // upgraded to a newer generator's layout. Projects scaffolded before
  // GENERATED_NOTE moved above CATALOG_START permanently keep it BETWEEN the
  // markers instead (surrounded by the blank lines buildSkill() puts around
  // it). Skip any leading blank lines and HTML-comment-only lines — blank so
  // a comment line is reachable however it is padded, and generically rather
  // than by matching GENERATED_NOTE's exact text — so that older layout still
  // yields "no lessons" instead of leaking the note as if it were a catalog
  // entry, and so this keeps working even if the note's wording changes later.
  const lines = rawBody.split('\n');
  let firstContentLine = 0;
  while (firstContentLine < lines.length) {
    const line = lines[firstContentLine].trim();
    if (line === '' || /^<!--.*-->$/.test(line)) {
      firstContentLine++;
    } else {
      break;
    }
  }
  const body = lines.slice(firstContentLine).join('\n').trim();

  return body === EMPTY_CATALOG ? '' : body;
}

function main() {
  try {
    const { skillPath } = resolvePaths();
    const skillContent = readFileSync(skillPath, 'utf8');
    const catalog = extractCatalog(skillContent);
    if (catalog) {
      process.stdout.write(`${catalog}\n`);
    }
  } catch {
    // SKILL.md missing, unreadable, or any other unexpected failure: stay
    // silent rather than risk breaking the session that invoked this hook.
  }
}

// Only run main() when executed as a CLI — importing this file (tests) must not.
if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(__dirname, 'lessons-index.mjs')
) {
  main();
}
